<?php

/*function d3_projection_views_plugins_alter(&$plugins) {
  dsm($plugins);
}*/

function d3_projection_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'd3_projection') . '/views',
  );
}

function template_preprocess_d3_projection_map(&$vars) {
  $path = drupal_get_path('module', 'd3_projection');

  // d3 libs
  drupal_add_js("http://d3js.org/d3.v3.min.js");
  drupal_add_js("http://d3js.org/topojson.v1.min.js");
  // Our data from the view
  drupal_add_js(array('d3Projection' => array('mapData' => _d3_projection_parse_rows($vars['rows']))), 'setting');
  // TopoJSON data.
  drupal_add_js(array('d3Projection' => array('pathToTopo' => $path . '/us.json')), 'setting');
  // The D3 scripts.
  drupal_add_js(drupal_get_path('module', 'd3_projection') . '/js/projection.js');
  // Styles for the map
  drupal_add_css($path . '/d3_projection.css');
}


function _d3_projection_parse_rows($rows) {
  $map_data = array();
  foreach($rows as $row) {
    $map_data[] = array(
      'node_title' => $row->node_title,
      'lon' => $row->field_field_geo_coords[0]['raw']['lon'],
      'lat' => $row->field_field_geo_coords[0]['raw']['lat'],
    );
  }
  return $map_data;
}
/**
 * Implements hook_theme().
 */
function d3_projection_theme($existing, $type, $theme, $path) {
  return array(
    'd3_projection_map' => array(
      'variables' => array('args' => NULL),
      'template' => 'views/d3-projection-map',
    ),
  );
}
